language: java
jdk:
  - openjdk15

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x ./gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r KAKAOMAP *
  - mkdir -p deploy
  - mv KAKAOMAP.zip deploy/KAKAOMAP.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kakaomap-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: kakaomap-build # S3 버킷
      key: KAKAOMAP.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: KAKAOMAP # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: KAKAOMAP # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - baugh248730@gmail.com