language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r kakaomap ./*
  - mkdir -p deploy
  - mv kakaomap.zip deploy/kakaomap.zip

deploy:
  - provider: s3
    access_key_id: AKIAJU3OEHT72IDEPPOA
    secret_access_key: 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

    bucket: kakaomap-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - baugh248730@gmail.com